events {}
http {
    # Отправляем access-логи в Logstash по протоколу syslog (UDP порт 5044)
    access_log syslog:server=logstash:5044,facility=local7,tag=nginx,severity=info;

    server {
        listen 80;
        server_name localhost;

        location / {
            proxy_pass http://kibana:5601;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}
