nput {
  syslog {
    port => 5044
    codec => "plain"
  }
}

filter {
  # Проверяем, что лог пришел от Nginx, и парсим его стандартный формат
  if [program] == "nginx" {
    grok {
      match => { "message" => "%{IPORHOST:clientip} - %{USER:auth} \[%{HTTPDATE:timestamp}\] \"(?>
    }
    date {
      match => [ "timestamp" , "dd/MMM/yyyy:HH:mm:ss Z" ]
      target => "@timestamp"
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "nginx-logs-%{+YYYY.MM.dd}"
  }
}
